version: '2.3'
services:
  postgres:
    image: shanelee007/docker-pact-postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      -  POSTGRES_PASSWORD=ThePostgresPassword
      -  POSTGRES_USER=admin
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "psql -h 'localhost' -U 'admin' -c '\\l'"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 40s
  pact:
    image: dius/pact-broker
    container_name: pact
    restart: unless-stopped
    environment:
      -  PACT_BROKER_DATABASE_NAME=pactbroker
      -  PACT_BROKER_DATABASE_PASSWORD=TheUserPassword
      -  PACT_BROKER_DATABASE_HOST=postgres
      -  PACT_BROKER_DATABASE_USERNAME=pactbrokeruser
    ports:
      - "80:80"
    depends_on:
      postgres:
          condition: service_healthy
